version: "3.3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "renas"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "newsletter"
    ports:
      - "5432:5432"
    volumes:
      - ./environment/config_db.sh:/docker-entrypoint-initdb.d/init_db.sh